spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: flight-booking-service
          uri: lb://FLIGHT-BOOKING-SERVICE
          predicates:
            - Path=/flight/**
        - id: flight-availability-service
          uri: lb://FLIGHT-AVAILABILITY-SERVICE
          predicates:
            - Path=/availability/**
    config:
      uri: http://localhost:8083
  config:
    import: "optional:configserver:http://localhost:8083"

server:
  port: 8082

